### ISSUE TITLE
Encrypt method id issue

### ISSUE THREAD

**Issue by TheSnowfield** [TheSnowfield/Konata#15]
In the OicqRequestCheckImage

### Konata
```
02
01 0C //length:268
1F 41
08 10
00 01
7A 41 93 C3
03 87 00 00 00 00 02 00 00 00 00 00 00 00 00
```

### Origin
```
02
01 0C //length:268
1F 41
08 10
00 01
7A 41 93 C3
03 07 00 00 00 00 02 00 00 00 00 00 00 00 00
```

0x87 is incorrect generated by Konata, It should be 0x07.

**Comment by takayama-lily** [comment]
这是新的ecdh算法？

**Comment by TheSnowfield** [comment]
> 这是新的ecdh算法？

no, It's just an issue about encrypt method id to select the share key to encrypt data.
ECDH algorithm not changed in the latest version.
