### ISSUE TITLE
fatal about jce parser

### ISSUE THREAD

**Issue by TheSnowfield** [TheSnowfield/Konata#38]
https://github.com/TheSnowfield/Konata/blob/f7fd99d432e68df325e18cf3b521f590dd1bae80/Konata.Library.JceStruct/JceTreeRoot.cs#L310

An exception will caused while any non-standard jce type(which are simple list, map, list) after the jce struct start/end.
The reason is the parser don't know the data length in the next jce non-standard type when decoding the bytes.

**This is fatal. Konata.Library.JceStruct must rewrite in the future.**

**Comment by takayama-lily** [comment]
you are cute
